import { EventEmitter } from 'events';
import {
  WorkerExecutionRequest,
  WorkerExecutionResult,
  ExecutionReport,
  ExecutionPlan,
  ExecutionArtifact,
  ExecutionStatus,
} from '../../contracts/iautonomous_worker';
import { WorkspaceEngine } from '../workspace/workspace_engine';
import { WorkspaceExecutionService } from './workspace_execution_service';
import { ReasoningCoordinator } from '../reasoning/reasoning_coordinator';
import { ExecutionResponseParser } from './execution_response_parser';
import { IEventStore } from '../../contracts/ievent_store';

/**
 * Delegates all reasoning to ReasoningCoordinator, which is also where the assigned worker's
 * activeExecution/history bookkeeping happens (via WorkerStore — see ADR-0005). This engine does
 * not duplicate that tracking; it only turns the reasoning response into real file mutations.
 */
export class WorkerExecutionEngine extends EventEmitter {
  private reports = new Map<string, ExecutionReport>();
  private responseParser: ExecutionResponseParser;

  constructor(
    private workspaceEngine: WorkspaceEngine,
    private workspaceExecutionService: WorkspaceExecutionService,
    private reasoningCoordinator: ReasoningCoordinator,
    private eventStore?: IEventStore,
    responseParser?: ExecutionResponseParser
  ) {
    super();
    this.responseParser = responseParser || new ExecutionResponseParser();
  }

  async executeTask(request: WorkerExecutionRequest): Promise<WorkerExecutionResult> {
    const startTime = Date.now();
    const executionId = request.executionId || `exec-${Date.now()}`;
    let status: ExecutionStatus = 'PREPARING_CONTEXT';

    this.emitEvent('WorkerExecutionStarted', executionId, {
      taskId: request.taskId,
      workerId: request.workerId,
      goal: request.goal,
    });

    try {
      // 1. Prepare Workspace
      const workspaceInfo = this.workspaceEngine.createWorkspace(request.taskId);
      const workspacePath = workspaceInfo.isolatedPath;

      // 2. Invoke Reasoning Pipeline
      status = 'REASONING';
      const reasoningRes = await this.reasoningCoordinator.requestReasoning({
        requestId: `req-${executionId}`,
        taskId: request.taskId,
        missionId: request.missionId,
        workerId: request.workerId,
        goal: this.buildCodeGenerationPrompt(request.goal, workspacePath),
        context: {
          constraints: [`Execute strictly within workspace '${workspacePath}'`],
        },
      });

      if (!reasoningRes.success || !reasoningRes.response) {
        throw new Error(reasoningRes.error || 'Reasoning pipeline failed to generate execution response');
      }

      // 3. Generate ExecutionPlan from the provider's actual response (zero direct file writes)
      status = 'PLANNING_MUTATIONS';
      const reasoningText = reasoningRes.response.responseText;
      const parsed = this.responseParser.parse(reasoningText);

      const plan: ExecutionPlan = parsed.hasStructuredOutput
        ? {
            planId: `plan-${executionId}`,
            taskId: request.taskId,
            workspacePath,
            summary: `Applied ${parsed.files.length} file(s) generated by the reasoning provider for goal: ${request.goal}`,
            filesToCreate: parsed.files,
            filesToModify: [],
          }
        : {
            // Honest fallback: the provider returned no `// FILE: <path>` blocks (prose-only
            // reply, refusal, or an unavailable-provider error message). Persist its raw
            // output for review instead of fabricating code that was never actually generated.
            planId: `plan-${executionId}`,
            taskId: request.taskId,
            workspacePath,
            summary: `Reasoning provider returned no structured file blocks for goal: ${request.goal}. Raw response saved to RESPONSE.md for review.`,
            filesToCreate: [
              {
                relativePath: 'RESPONSE.md',
                content: `# Task ${request.taskId}\n\nGoal: ${request.goal}\n\n> No \`// FILE: <path>\` code blocks were found in the provider response below.\n\n---\n\n${reasoningText}\n`,
              },
            ],
            filesToModify: [],
          };

      // 4. Delegate Filesystem Mutations to WorkspaceExecutionService
      status = 'EXECUTING_MUTATIONS';
      const mutationRes = this.workspaceExecutionService.applyExecutionPlan(plan);

      if (!mutationRes.success) {
        throw new Error(mutationRes.error || 'WorkspaceExecutionService failed to apply execution plan');
      }

      // 5. Harvest Artifacts
      status = 'COLLECTING_ARTIFACTS';
      const artifacts: ExecutionArtifact[] = [...mutationRes.artifacts];

      // Add Reasoning Summary Artifact
      artifacts.push({
        artifactId: `art-reasoning-${executionId}`,
        type: 'REASONING_SUMMARY',
        path: `${workspacePath}/reasoning_summary.json`,
        content: JSON.stringify(reasoningRes.response, null, 2),
        sizeBytes: Buffer.byteLength(JSON.stringify(reasoningRes.response), 'utf8'),
        createdAt: new Date().toISOString(),
      });

      // Add Execution Log Artifact
      const logContent = `[EXECUTION LOG - ${new Date().toISOString()}]\nTask: ${request.taskId}\nWorker: ${request.workerId}\nFiles Created: ${mutationRes.createdFiles.length}\nDuration: ${Date.now() - startTime}ms\n`;
      artifacts.push({
        artifactId: `art-log-${executionId}`,
        type: 'EXECUTION_LOG',
        path: `${workspacePath}/execution.log`,
        content: logContent,
        sizeBytes: Buffer.byteLength(logContent, 'utf8'),
        createdAt: new Date().toISOString(),
      });

      this.emitEvent('ArtifactsGenerated', executionId, {
        artifactCount: artifacts.length,
        taskId: request.taskId,
      });

      // 6. Compile ExecutionReport
      status = 'COMPLETED';
      const durationMs = Date.now() - startTime;
      const report: ExecutionReport = {
        executionId,
        taskId: request.taskId,
        workerId: request.workerId,
        status,
        summary: `Worker ${request.workerId} successfully executed task '${request.taskId}' in isolated workspace '${workspacePath}'`,
        recommendations: [
          'Run verification engine tests on generated workspace files',
          'Prepare dry-run merge inspection for master integration',
        ],
        artifacts,
        durationMs,
        filesCreated: mutationRes.createdFiles,
        filesModified: mutationRes.modifiedFiles,
        reasoningResponse: reasoningRes.response,
      };

      this.reports.set(executionId, report);
      this.emitEvent('WorkerExecutionCompleted', executionId, {
        taskId: request.taskId,
        workerId: request.workerId,
        durationMs,
        filesCreatedCount: mutationRes.createdFiles.length,
      });

      return { success: true, report };
    } catch (err: any) {
      status = 'FAILED';
      const durationMs = Date.now() - startTime;
      this.emitEvent('WorkerExecutionFailed', executionId, {
        taskId: request.taskId,
        workerId: request.workerId,
        reason: err.message,
        durationMs,
      });

      const report: ExecutionReport = {
        executionId,
        taskId: request.taskId,
        workerId: request.workerId,
        status,
        summary: `Worker execution failed: ${err.message}`,
        recommendations: ['Check workspace permissions and retry task'],
        artifacts: [],
        durationMs,
        filesCreated: [],
        filesModified: [],
      };

      this.reports.set(executionId, report);
      return { success: false, report, error: err.message };
    }
  }

  getReport(executionId: string): ExecutionReport | undefined {
    return this.reports.get(executionId);
  }

  listReports(): ExecutionReport[] {
    return Array.from(this.reports.values());
  }

  private buildCodeGenerationPrompt(goal: string, workspacePath: string): string {
    return [
      goal,
      '',
      `You are generating source files inside the isolated workspace directory '${workspacePath}'.`,
      'Respond with one or more fenced code blocks and no prose outside of them.',
      'The first line inside each fenced code block MUST declare its destination using the exact form:',
      '// FILE: relative/path/to/file.ext',
      '(use the comment syntax appropriate to the file type, e.g. "# FILE: path" for YAML/shell, "<!-- FILE: path -->" for Markdown/HTML).',
      'Paths must be relative to the workspace root — never absolute, never containing "..".',
    ].join('\n');
  }

  private emitEvent(eventType: string, aggregateId: string, payload: any): void {
    const evt = {
      eventId: `evt-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      aggregateId,
      eventType,
      version: 1,
      timestamp: new Date().toISOString(),
      actorId: 'WorkerExecutionEngine',
      payload,
    };
    this.emit(eventType, evt);
    if (this.eventStore) {
      this.eventStore.append(evt).catch(() => {});
    }
  }
}
