import { DashboardState } from '../types/dashboard';

export class SeOsApiService {
  private static initialMockState: DashboardState = {
    projectId: 'proj-1784894242694',
    businessGoal: 'Create a REST API for User Management',
    projectStatus: 'COMPLETED',
    progressPercent: 100,
    tasks: [
      {
        id: 't-mission-101',
        missionId: 'mission-001',
        title: 'Design System Architecture',
        description: 'Define microservices architecture, endpoints, and interface boundaries',
        requiredCapability: 'Architecture',
        priority: 'P0',
        status: 'COMPLETED',
        dependencies: [],
        assignedDepartmentId: 'dept-architecture',
        assignedWorkerId: 'emp-alice',
        estimatedComplexity: 2,
      },
      {
        id: 't-mission-102',
        missionId: 'mission-001',
        title: 'Define Database Schema & Data Models',
        description: 'Create SQLite table schemas, migrations, and TypeScript models',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'COMPLETED',
        dependencies: ['t-mission-101'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 3,
      },
      {
        id: 't-mission-103',
        missionId: 'mission-001',
        title: 'Implement Express REST Server Endpoints',
        description: 'Implement CRUD controllers, services, and route handlers',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'COMPLETED',
        dependencies: ['t-mission-101', 't-mission-102'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 4,
      },
      {
        id: 't-mission-104',
        missionId: 'mission-001',
        title: 'Implement Auth & Permissions Middleware',
        description: 'Add JWT verification and role-based access control',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'COMPLETED',
        dependencies: ['t-mission-103'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 3,
      },
      {
        id: 't-mission-105',
        missionId: 'mission-001',
        title: 'Write Verification Unit & Integration Tests',
        description: 'Create test suites covering API routes and auth middleware',
        requiredCapability: 'QA',
        priority: 'P2',
        status: 'COMPLETED',
        dependencies: ['t-mission-104'],
        assignedDepartmentId: 'dept-qa',
        assignedWorkerId: 'emp-charlie',
        estimatedComplexity: 2,
      },
      {
        id: 't-mission-106',
        missionId: 'mission-001',
        title: 'Generate OpenAPI Specs & Documentation',
        description: 'Produce OpenAPI v3 specification and developer guide',
        requiredCapability: 'Documentation',
        priority: 'P2',
        status: 'COMPLETED',
        dependencies: ['t-mission-104'],
        assignedDepartmentId: 'dept-documentation',
        assignedWorkerId: 'emp-doc-lead',
        estimatedComplexity: 1,
      },
    ],
    workers: [
      {
        id: 'emp-alice',
        name: 'Alice',
        role: 'Lead Architect',
        departmentId: 'dept-architecture',
        departmentName: 'Architecture',
        status: 'IDLE',
        currentTaskId: 't-mission-101',
        currentTaskTitle: 'Design System Architecture',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-mission-101',
        durationMs: 1420,
      },
      {
        id: 'emp-bob',
        name: 'Bob',
        role: 'Backend Engineer',
        departmentId: 'dept-backend',
        departmentName: 'Backend',
        status: 'IDLE',
        currentTaskId: 't-mission-104',
        currentTaskTitle: 'Implement Auth & Permissions Middleware',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-mission-104',
        durationMs: 3100,
      },
      {
        id: 'emp-charlie',
        name: 'Charlie',
        role: 'QA Engineer',
        departmentId: 'dept-qa',
        departmentName: 'QA',
        status: 'IDLE',
        currentTaskId: 't-mission-105',
        currentTaskTitle: 'Write Verification Unit & Integration Tests',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-mission-105',
        durationMs: 2050,
      },
    ],
    aiSessions: [
      {
        sessionId: 'session-emp-bob-1784894243629',
        workerId: 'emp-bob',
        workerName: 'Bob (Backend Lead)',
        providerName: 'Claude Code CLI (Runtime Plugin)',
        prompt: 'Implement Auth & Permissions Middleware for REST API User Management',
        streamingOutput: [
          'Reading workspace configuration...',
          'Analyzing routes in src/routes/user.routes.ts...',
          'Generating AuthMiddleware class with JWT validation...',
          'Writing middleware implementation to workspace index.ts...',
          'Verification check requested...',
          'Execution complete (3100ms)',
        ],
        finalResponse: '[Claude Code CLI Output] Processed prompt: Implement Auth & Permissions Middleware. Generated 2 workspace files.',
        durationMs: 3100,
        tokenUsage: 142,
        status: 'COMPLETED',
        startedAt: '2026-07-24T12:04:23.000Z',
      },
      {
        sessionId: 'session-emp-charlie-1784894243631',
        workerId: 'emp-charlie',
        workerName: 'Charlie (QA Engineer)',
        providerName: 'Claude Code CLI (Runtime Plugin)',
        prompt: 'Create test suites covering API routes and middleware for User Management',
        streamingOutput: [
          'Scanning test environment...',
          'Generating Jest test assertions...',
          'Writing user.test.ts to test suite...',
          'Task execution complete.',
        ],
        finalResponse: '[Claude Code CLI Output] Processed prompt: Create test suites covering API routes. 6 tests passed.',
        durationMs: 2050,
        tokenUsage: 98,
        status: 'COMPLETED',
        startedAt: '2026-07-24T12:04:24.000Z',
      },
    ],
    eventStream: [
      {
        eventId: 'evt-2001',
        aggregateId: 'proj-1784894242694',
        eventType: 'ProjectExecutionStarted',
        timestamp: '2026-07-24T12:04:20.100Z',
        actorId: 'ProjectLifecycleOrchestrator',
        payload: { goal: 'Create a REST API for User Management' },
      },
      {
        eventId: 'evt-2002',
        aggregateId: 'mission-001',
        eventType: 'MissionDecomposed',
        timestamp: '2026-07-24T12:04:21.050Z',
        actorId: 'MissionDecomposer',
        payload: { tasksCount: 6, batchesCount: 5 },
      },
      {
        eventId: 'evt-2003',
        aggregateId: 't-mission-101',
        eventType: 'TaskAssigned',
        timestamp: '2026-07-24T12:04:21.200Z',
        actorId: 'TaskAssignmentEngine',
        payload: { workerId: 'emp-alice', departmentId: 'dept-architecture' },
      },
      {
        eventId: 'evt-2004',
        aggregateId: 't-mission-104',
        eventType: 'TaskExecutionStarted',
        timestamp: '2026-07-24T12:04:23.000Z',
        actorId: 'MissionExecutionOrchestrator',
        payload: { workerId: 'emp-bob' },
      },
      {
        eventId: 'evt-2005',
        aggregateId: 't-mission-104',
        eventType: 'VerificationPassed',
        timestamp: '2026-07-24T12:04:24.500Z',
        actorId: 'VerificationPipeline',
        payload: { qualityScore: 100, passedStepsCount: 6 },
      },
      {
        eventId: 'evt-2006',
        aggregateId: 'proj-1784894242694',
        eventType: 'ProjectExecutionCompleted',
        timestamp: '2026-07-24T12:04:25.000Z',
        actorId: 'ProjectLifecycleOrchestrator',
        payload: { summary: 'Tasks executed: 6/6 successfully.' },
      },
    ],
    artifacts: [
      {
        artifactId: 'art-create-101',
        type: 'CREATED_FILE',
        path: './.se_workspaces/ws-t-mission-104/index.ts',
        sizeBytes: 420,
        createdAt: '2026-07-24T12:04:23.500Z',
        contentSnippet: 'export function authMiddleware(req, res, next) { /* JWT verification */ }',
      },
      {
        artifactId: 'art-create-102',
        type: 'CREATED_FILE',
        path: './.se_workspaces/ws-t-mission-104/README.md',
        sizeBytes: 250,
        createdAt: '2026-07-24T12:04:23.600Z',
        contentSnippet: '# User Management REST API - Middleware Documentation',
      },
      {
        artifactId: 'art-log-103',
        type: 'EXECUTION_LOG',
        path: './.se_workspaces/ws-t-mission-104/execution.log',
        sizeBytes: 128,
        createdAt: '2026-07-24T12:04:23.700Z',
        contentSnippet: '[EXECUTION LOG] Task t-mission-104 executed by Bob (dept-backend). 2 files created.',
      },
      {
        artifactId: 'art-summary-104',
        type: 'REASONING_SUMMARY',
        path: './.se_workspaces/ws-t-mission-104/reasoning_summary.json',
        sizeBytes: 680,
        createdAt: '2026-07-24T12:04:23.800Z',
        contentSnippet: '{"requestId": "req-104", "pluginId": "plugin-claude-code", "durationMs": 3100, "tokenUsage": 142}',
      },
    ],
    verification: {
      status: 'PASSED',
      qualityScore: 100,
      passedStepsCount: 6,
      totalStepsCount: 6,
      steps: [
        { name: 'WorkspaceExistenceCheck', category: 'Workspace', passed: true, message: 'Workspace directory exists.', durationMs: 1 },
        { name: 'ArtifactIntegrityCheck', category: 'Artifacts', passed: true, message: 'Found 4 valid artifacts.', durationMs: 1 },
        { name: 'BuildValidationCheck', category: 'Build', passed: true, message: 'Build check passed.', durationMs: 2 },
        { name: 'TypeScriptCompilationCheck', category: 'TypeCheck', passed: true, message: 'TypeScript compilation check passed.', durationMs: 3 },
        { name: 'UnitTestExecutionCheck', category: 'Testing', passed: true, message: 'Unit tests passed.', durationMs: 4 },
        { name: 'LintValidationCheck', category: 'Linting', passed: true, message: 'Lint rules passed.', durationMs: 2 },
      ],
      errors: [],
    },
  };

  static fetchDashboardState(): DashboardState {
    return this.initialMockState;
  }
}
