import { DashboardState } from '../types/dashboard';

export class SeOsApiService {
  private static mockState: DashboardState = {
    projectId: 'proj-1784894242694',
    businessGoal: 'Create a REST API for User Management',
    projectStatus: 'EXECUTING',
    currentStage: 'Stage 4 / 5 — Integration Testing & Documentation',
    estimatedCompletionMinutes: 2,
    progressPercent: 80,
    systemHealth: {
      kernelStatus: 'ONLINE',
      runtimeProvider: 'Claude Code CLI v2.1.218',
      totalWorkersCount: 6,
      runningTasksCount: 2,
      queuedTasksCount: 3,
      memoryUsageMB: 482,
      cpuLoadPercent: 12.4,
    },
    tasks: [
      {
        id: 't-101',
        missionId: 'm-001',
        title: 'Design System Architecture',
        description: 'Define microservices architecture, endpoints, and interface boundaries',
        requiredCapability: 'Architecture',
        priority: 'P0',
        status: 'COMPLETED',
        dependencies: [],
        assignedDepartmentId: 'dept-architecture',
        assignedWorkerId: 'emp-alice',
        estimatedComplexity: 2,
      },
      {
        id: 't-102',
        missionId: 'm-001',
        title: 'Define DB Schema & Models',
        description: 'Create SQLite table schemas, migrations, and TypeScript models',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'COMPLETED',
        dependencies: ['t-101'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 3,
      },
      {
        id: 't-103',
        missionId: 'm-001',
        title: 'Implement Express REST Server Endpoints',
        description: 'Implement CRUD controllers, services, and route handlers',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'COMPLETED',
        dependencies: ['t-101', 't-102'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 4,
      },
      {
        id: 't-104',
        missionId: 'm-001',
        title: 'Implement Auth & Permissions Middleware',
        description: 'Add JWT verification and role-based access control',
        requiredCapability: 'Backend',
        priority: 'P1',
        status: 'RUNNING',
        dependencies: ['t-103'],
        assignedDepartmentId: 'dept-backend',
        assignedWorkerId: 'emp-bob',
        estimatedComplexity: 3,
      },
      {
        id: 't-105',
        missionId: 'm-001',
        title: 'Write Verification Unit & Integration Tests',
        description: 'Create test suites covering API routes and auth middleware',
        requiredCapability: 'QA',
        priority: 'P2',
        status: 'RUNNING',
        dependencies: ['t-104'],
        assignedDepartmentId: 'dept-qa',
        assignedWorkerId: 'emp-charlie',
        estimatedComplexity: 2,
      },
      {
        id: 't-106',
        missionId: 'm-001',
        title: 'Generate OpenAPI Specs & Documentation',
        description: 'Produce OpenAPI v3 specification and developer guide',
        requiredCapability: 'Documentation',
        priority: 'P2',
        status: 'READY',
        dependencies: ['t-104'],
        assignedDepartmentId: 'dept-documentation',
        assignedWorkerId: 'emp-doc-lead',
        estimatedComplexity: 1,
      },
    ],
    workers: [
      {
        id: 'emp-alice',
        name: 'Alice',
        role: 'Lead Architect',
        departmentId: 'dept-architecture',
        departmentName: 'Architecture',
        status: 'IDLE',
        currentTaskId: 't-101',
        currentTaskTitle: 'Design System Architecture',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-101',
        durationMs: 1420,
      },
      {
        id: 'emp-bob',
        name: 'Bob',
        role: 'Backend Engineer',
        departmentId: 'dept-backend',
        departmentName: 'Backend',
        status: 'EXECUTING',
        currentTaskId: 't-104',
        currentTaskTitle: 'Implement Auth Middleware',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-104',
        durationMs: 3100,
      },
      {
        id: 'emp-charlie',
        name: 'Charlie',
        role: 'QA Engineer',
        departmentId: 'dept-qa',
        departmentName: 'QA',
        status: 'EXECUTING',
        currentTaskId: 't-105',
        currentTaskTitle: 'Write Verification Tests',
        runtimeProvider: 'Claude Code CLI v2.1',
        currentWorkspace: './.se_workspaces/ws-t-105',
        durationMs: 2050,
      },
    ],
    aiSessions: [
      {
        sessionId: 'session-emp-bob-1784894243629',
        workerId: 'emp-bob',
        workerName: 'Bob (Backend Engineer)',
        providerName: 'Claude Code CLI',
        prompt: 'Implement Auth & Permissions Middleware for REST API User Management in TypeScript',
        streamingOutput: [
          '[PtyTransport] Executing process: claude --interactive',
          '[Claude CLI] Reading workspace directory structure at ./.se_workspaces/ws-t-104...',
          '[Claude CLI] Analyzing user routes in src/routes/user.routes.ts...',
          '[Claude CLI] Writing AuthMiddleware class with JWT verification...',
          '[Claude CLI] File written: src/middleware/auth.middleware.ts (248 lines added)',
          '[Claude CLI] Invoking tool: write_file(src/middleware/auth.middleware.ts)',
          '[VerificationPipeline] Running auto-verification checks...',
          '[VerificationPipeline] TypeScript compilation: PASSED (0 errors)',
        ],
        finalResponse: 'Successfully generated AuthMiddleware with JWT verification and RBAC roles. Created src/middleware/auth.middleware.ts.',
        toolCalls: [
          { toolName: 'read_file', arguments: { path: 'src/routes/user.routes.ts' }, durationMs: 12, status: 'SUCCESS' },
          { toolName: 'write_file', arguments: { path: 'src/middleware/auth.middleware.ts' }, durationMs: 45, status: 'SUCCESS' },
        ],
        durationMs: 3100,
        tokenUsage: 1420,
        workspacePath: './.se_workspaces/ws-t-104',
        status: 'STREAMING',
        startedAt: '2026-07-24T12:04:23.000Z',
      },
      {
        sessionId: 'session-emp-charlie-1784894243631',
        workerId: 'emp-charlie',
        workerName: 'Charlie (QA Engineer)',
        providerName: 'Claude Code CLI',
        prompt: 'Create Jest unit test suites covering user routes and auth middleware',
        streamingOutput: [
          '[PtyTransport] Connected worker process session-emp-charlie',
          '[Claude CLI] Generating test assertions for AuthMiddleware...',
          '[Claude CLI] Writing tests/user_auth.test.ts (110 lines added)',
          '[VerificationPipeline] Running Jest test suite...',
          '[VerificationPipeline] Test suite execution: 6 tests PASSED',
        ],
        finalResponse: 'Generated 6 Jest unit tests covering JWT token validation, expired token rejection, and role authorization.',
        toolCalls: [
          { toolName: 'write_file', arguments: { path: 'tests/user_auth.test.ts' }, durationMs: 38, status: 'SUCCESS' },
        ],
        durationMs: 2050,
        tokenUsage: 980,
        workspacePath: './.se_workspaces/ws-t-105',
        status: 'COMPLETED',
        startedAt: '2026-07-24T12:04:24.000Z',
      },
      {
        sessionId: 'session-emp-alice-1784894243620',
        workerId: 'emp-alice',
        workerName: 'Alice (Lead Architect)',
        providerName: 'Claude Code CLI',
        prompt: 'Design System Architecture and microservices DAG execution plan',
        streamingOutput: [
          '[PtyTransport] Process started: claude --print',
          '[Claude CLI] Generating system architecture document...',
          '[Claude CLI] Created architecture_blueprint.md',
        ],
        finalResponse: 'System architecture blueprint created successfully.',
        toolCalls: [
          { toolName: 'write_file', arguments: { path: 'docs/architecture_blueprint.md' }, durationMs: 25, status: 'SUCCESS' },
        ],
        durationMs: 1420,
        tokenUsage: 650,
        workspacePath: './.se_workspaces/ws-t-101',
        status: 'COMPLETED',
        startedAt: '2026-07-24T12:04:20.000Z',
      },
    ],
    eventStream: [
      {
        eventId: 'evt-2006',
        aggregateId: 't-105',
        eventType: 'TaskExecutionCompleted',
        timestamp: '2026-07-24T12:57:45.100Z',
        actorId: 'MissionExecutionOrchestrator',
        payload: { taskId: 't-105', workerId: 'emp-charlie' },
      },
      {
        eventId: 'evt-2005',
        aggregateId: 't-104',
        eventType: 'VerificationPassed',
        timestamp: '2026-07-24T12:57:40.500Z',
        actorId: 'VerificationPipeline',
        payload: { qualityScore: 100, passedStepsCount: 6 },
      },
      {
        eventId: 'evt-2004',
        aggregateId: 't-104',
        eventType: 'TaskExecutionStarted',
        timestamp: '2026-07-24T12:57:30.000Z',
        actorId: 'MissionExecutionOrchestrator',
        payload: { workerId: 'emp-bob' },
      },
      {
        eventId: 'evt-2003',
        aggregateId: 't-104',
        eventType: 'TaskAssigned',
        timestamp: '2026-07-24T12:57:25.200Z',
        actorId: 'TaskAssignmentEngine',
        payload: { workerId: 'emp-bob', departmentId: 'dept-backend' },
      },
      {
        eventId: 'evt-2002',
        aggregateId: 'm-001',
        eventType: 'MissionDecomposed',
        timestamp: '2026-07-24T12:57:20.050Z',
        actorId: 'MissionDecomposer',
        payload: { tasksCount: 6, batchesCount: 5 },
      },
      {
        eventId: 'evt-2001',
        aggregateId: 'proj-1784894242694',
        eventType: 'ProjectExecutionStarted',
        timestamp: '2026-07-24T12:57:15.100Z',
        actorId: 'ProjectLifecycleOrchestrator',
        payload: { goal: 'Create a REST API for User Management' },
      },
    ],
    fileChanges: [
      {
        path: 'src/middleware/auth.middleware.ts',
        status: 'CREATED',
        additions: 248,
        deletions: 0,
        fileSizeBytes: 4200,
        diffSnippet: 'export class AuthMiddleware {\n+  async verifyJwt(req: Request, res: Response) {\n+    const token = req.headers.authorization?.split(" ")[1];\n+    if (!token) return res.status(401).json({ error: "Unauthorized" });\n+  }\n+}',
      },
      {
        path: 'tests/user_auth.test.ts',
        status: 'CREATED',
        additions: 110,
        deletions: 0,
        fileSizeBytes: 2150,
        diffSnippet: 'describe("AuthMiddleware Tests", () => {\n+  it("should return 401 if authorization header is missing", async () => {\n+    const res = await request(app).get("/api/users/profile");\n+    expect(res.status).toBe(401);\n+  });\n+});',
      },
      {
        path: 'src/routes/user.routes.ts',
        status: 'MODIFIED',
        additions: 34,
        deletions: 12,
        fileSizeBytes: 1800,
        diffSnippet: ' router.get("/profile", \n-  legacyAuthCheck,\n+  authMiddleware.verifyJwt,\n   userController.getProfile\n );',
      },
    ],
    verification: {
      status: 'PASSED',
      qualityScore: 100,
      passedStepsCount: 6,
      totalStepsCount: 6,
      steps: [
        { name: 'WorkspaceExistenceCheck', category: 'Workspace', passed: true, message: 'Workspace directory exists.', durationMs: 1 },
        { name: 'ArtifactIntegrityCheck', category: 'Artifacts', passed: true, message: 'Found 4 valid artifacts.', durationMs: 1 },
        { name: 'BuildValidationCheck', category: 'Build', passed: true, message: 'Build check passed cleanly.', durationMs: 2 },
        { name: 'TypeScriptCompilationCheck', category: 'TypeCheck', passed: true, message: 'TypeScript compilation check passed (0 errors).', durationMs: 3 },
        { name: 'UnitTestExecutionCheck', category: 'Testing', passed: true, message: '6 unit tests passed.', durationMs: 4 },
        { name: 'LintValidationCheck', category: 'Linting', passed: true, message: 'Lint rules compliant.', durationMs: 2 },
      ],
      errors: [],
    },
    systemConsoleLogs: [
      { id: 'log-1', timestamp: '12:57:15', level: 'INFO', message: '[Kernel] SE-OS v2.0 booted cleanly (SQLite EventStore & SharedMemory connected)' },
      { id: 'log-2', timestamp: '12:57:20', level: 'SUCCESS', message: '[MissionDecomposer] Decomposed goal into 6 tasks across 5 DAG batches' },
      { id: 'log-3', timestamp: '12:57:25', level: 'INFO', message: '[TaskAssignmentEngine] Assigned task t-104 to worker emp-bob (dept-backend)' },
      { id: 'log-4', timestamp: '12:57:30', level: 'SUCCESS', message: '[PtyTransport] Worker emp-bob session attached to Claude Code CLI v2.1' },
      { id: 'log-5', timestamp: '12:57:40', level: 'SUCCESS', message: '[VerificationPipeline] Task t-104 passed quality gates (100/100 score)' },
    ],
  };

  static fetchDashboardState(): DashboardState {
    return this.mockState;
  }
}
