import { EventEmitter } from 'events';
import { ChildProcess } from 'child_process';
import { ClaudeCodeRuntimePlugin, ClaudeProcessSpawner } from '../../../src/v2/application/plugins/claude/claude_code_runtime_plugin';
import {
  ClaudeCliDetector,
  ClaudeCliDetectionResult,
} from '../../../src/v2/application/plugins/claude/claude_cli_detector';
import { CliDetector, CliDetectionResult } from '../../../src/v2/application/plugins/cli_detector';
import { SeOsCliProviderOverrides } from '../../../src/v2/cli/se_os_cli';
import { IEventStore } from '../../../src/v2/contracts/ievent_store';
import { CliSpawnOptions } from '../../../src/v2/application/plugins/cli_process_executor';

/**
 * Multiple real AI provider CLIs (not just claude) may genuinely be installed on the machine
 * running this suite — e.g. this sandbox also has real `codex`/`gemini` binaries on PATH. Any
 * test that calls Kernel.registerDefaultProviders()/constructs a SeOsCli must guarantee zero
 * live calls to ALL of them, not just Claude. FakeCliDetector always reports "not installed" for
 * the whole provider catalog so their execute() short-circuits honestly without ever spawning.
 */
export class FakeCliDetector extends CliDetector {
  constructor(private result: CliDetectionResult) {
    super('fake-cli');
  }
  detect(): CliDetectionResult {
    return this.result;
  }
}

/** Bundles safe fakes for every provider (Claude + the whole catalog) for use with
 * `new SeOsCli(...)` or `kernel.registerDefaultProviders(...)` in tests. */
export function createSafeTestProviderOverrides(claudeOptions?: {
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  available?: boolean;
  recorder?: FakeClaudeSpawnRecorder;
}): SeOsCliProviderOverrides {
  return {
    claudeSpawner: createFakeClaudeSpawner(claudeOptions),
    claudeDetector: claudeOptions?.available === false ? createUnavailableDetector() : createAvailableDetector(),
    catalogSpawner: createFakeClaudeSpawner(),
    catalogDetectorFactory: () => new FakeCliDetector({ available: false, error: 'not installed (test fake)' }),
  };
}

/**
 * Detection also has to be faked: whether `claude` happens to be on the PATH of the machine
 * running the test suite must never change test outcomes. Subclassing (rather than a plain
 * object literal) preserves TypeScript's nominal compatibility with ClaudeCliDetector.
 */
export class FakeClaudeCliDetector extends ClaudeCliDetector {
  constructor(private result: ClaudeCliDetectionResult) {
    super();
  }
  detect(): ClaudeCliDetectionResult {
    return this.result;
  }
}

export function createAvailableDetector(executablePath = '/fake/bin/claude'): FakeClaudeCliDetector {
  return new FakeClaudeCliDetector({ available: true, executablePath, version: 'claude-fake/1.0.0' });
}

export function createUnavailableDetector(error = 'claude CLI not found (fake)'): FakeClaudeCliDetector {
  return new FakeClaudeCliDetector({ available: false, error });
}

/**
 * ClaudeCodeRuntimePlugin now really shells out to the `claude` executable. These tests must
 * stay fast, deterministic, and free of live API calls, so every test that registers the plugin
 * injects one of these fakes instead of letting it fall back to a real child_process.spawn.
 */
class FakeChildProcess extends EventEmitter {
  stdout = new EventEmitter();
  stderr = new EventEmitter();
  killed = false;
  kill(): boolean {
    this.killed = true;
    return true;
  }
}

export interface FakeClaudeSpawnCall {
  executable: string;
  args: string[];
  cwd?: string;
  env?: NodeJS.ProcessEnv;
}

export interface FakeClaudeSpawnRecorder {
  calls: FakeClaudeSpawnCall[];
}

export function createSpawnRecorder(): FakeClaudeSpawnRecorder {
  return { calls: [] };
}

export const DEFAULT_FAKE_CLAUDE_STDOUT = `Here is the generated module:

\`\`\`typescript
// FILE: index.ts
export function main(): void {
  console.log("ok");
}
\`\`\`

\`\`\`markdown
// FILE: README.md
# Generated Module

Autogenerated by the fake Claude test spawner.
\`\`\`
`;

export function createFakeClaudeCodeRuntimePlugin(options: {
  eventStore?: IEventStore;
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  available?: boolean;
  recorder?: FakeClaudeSpawnRecorder;
} = {}): ClaudeCodeRuntimePlugin {
  const { eventStore, stdout, stderr, exitCode, available = true, recorder } = options;
  const spawner = createFakeClaudeSpawner({ stdout, stderr, exitCode, recorder });
  const detector = available ? createAvailableDetector() : createUnavailableDetector();
  return new ClaudeCodeRuntimePlugin(eventStore, spawner, detector);
}

export function createFakeClaudeSpawner(options: {
  stdout?: string;
  stderr?: string;
  exitCode?: number;
  recorder?: FakeClaudeSpawnRecorder;
} = {}): ClaudeProcessSpawner {
  const { stdout = DEFAULT_FAKE_CLAUDE_STDOUT, stderr = '', exitCode = 0, recorder } = options;

  return (executable: string, args: string[], spawnOptions?: CliSpawnOptions) => {
    if (recorder) recorder.calls.push({ executable, args, cwd: spawnOptions?.cwd, env: spawnOptions?.env });
    const child = new FakeChildProcess();
    // Defer so .on()/.stdout.on() listeners registered right after spawn() returns are attached
    // first — mirrors how a real child process emits data asynchronously.
    setImmediate(() => {
      if (stdout) child.stdout.emit('data', Buffer.from(stdout, 'utf8'));
      if (stderr) child.stderr.emit('data', Buffer.from(stderr, 'utf8'));
      child.emit('close', exitCode);
    });
    return child as unknown as ChildProcess;
  };
}
